# Generated by Django 2.2.9 on 2023-08-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
