# Generated by Django 2.2.9 on 2023-08-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_meeting_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meeting_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
