# Generated by Django 3.2.20 on 2023-08-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_presence'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='type',
            field=models.CharField(choices=[('OFF', 'Offline'), ('ON', 'Online')], default=1, max_length=300),
            preserve_default=False,
        ),
    ]
