# Generated by Django 3.2.20 on 2023-08-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_meeting_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='type',
            field=models.CharField(blank=True, choices=[('OFF', 'Offline'), ('ON', 'Online')], max_length=300, null=True),
        ),
    ]
