# Generated by Django 3.2.20 on 2023-08-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0006_alter_meeting_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='price',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
