# Generated by Django 3.2.20 on 2023-10-01 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0007_meeting_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presence',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='meetings.meeting'),
        ),
        migrations.AlterField(
            model_name='presence',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presences', to=settings.AUTH_USER_MODEL),
        ),
    ]
