# Generated by Django 3.2.20 on 2023-10-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0009_auto_20231001_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='np_panel',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
