# Generated by Django 3.2.20 on 2023-10-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panelcreator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='paid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
