# Generated by Django 3.2.20 on 2023-10-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panelcreator', '0003_remove_creator_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='paid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
