# Generated by Django 3.2.20 on 2023-08-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='date_start',
            field=models.DateTimeField(),
        ),
    ]
