# Generated by Django 3.2.20 on 2023-08-15 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0006_alter_meeting_type'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='meeting',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Meeting', to='meetings.meeting'),
            preserve_default=False,
        ),
    ]
