# Generated by Django 3.2.20 on 2023-08-15 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0002_key_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_key', to='auth.user'),
            preserve_default=False,
        ),
    ]
