# Generated by Django 3.2.20 on 2023-08-15 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_key_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='key',
            name='link',
        ),
    ]
