# Generated by Django 3.2.20 on 2023-08-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_remove_key_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='link',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
